using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace MedInsight.Services
{
    public class PredictionService
    {
        private readonly HttpClient _httpClient;
        private readonly IConfiguration _configuration;

        public PredictionService(HttpClient httpClient, IConfiguration configuration)
        {
            _httpClient = httpClient;
            _configuration = configuration;
        }

        public async Task<string> GetPredictionAsync(
            int Itching,
            int SkinRash,
            int NodalSkinEruptions,
            int ContinuousSneezing,
            int Shivering,
            int Chills,
            int JointPain,
            int StomachPain,
            int Acidity,
            int UlcersOnTongue,
            int MuscleWasting,
            int Vomiting,
            int BurningMicturition,
            int SpottingUrination,
            int Fatigue,
            int WeightGain,
            int Anxiety,
            int ColdHandsAndFeet,
            int MoodSwings,
            int WeightLoss,
            int Restlessness,
            int Lethargy,
            int PatchesInThroat,
            int IrregularSugarLevel,
            int Cough,
            int HighFever,
            int SunkenEyes,
            int Breathlessness,
            int Sweating,
            int Dehydration,
            int Indigestion,
            int Headache,
            int YellowishSkin,
            int DarkUrine,
            int Nausea,
            int LossOfAppetite,
            int PainBehindTheEyes,
            int BackPain,
            int Constipation,
            int AbdominalPain,
            int Diarrhea,
            int MildFever,
            int YellowUrine,
            int YellowingOfEyes,
            int AcuteLiverFailure,
            int SwellingOfStomach,
            int SwelledLymphNodes,
            int Malaise,
            int BlurredAndDistortedVision,
            int Phlegm,
            int ThroatIrritation,
            int RednessOfEyes,
            int SinusPressure,
            int RunnyNose,
            int Congestion,
            int ChestPain,
            int WeaknessInLimbs,
            int FastHeartRate,
            int PainDuringBowelMovements,
            int PainInAnalRegion,
            int BloodyStool,
            int IrritationInAnus,
            int NeckPain,
            int Dizziness,
            int Cramps,
            int Bruising,
            int Obesity,
            int SwollenLegs,
            int SwollenBloodVessels,
            int PuffyFaceAndEyes,
            int EnlargedThyroid,
            int BrittleNails,
            int SwollenExtremeties,
            int ExcessiveHunger,
            int ExtraMaritalContacts,
            int DryingAndTinglingLips,
            int SlurredSpeech,
            int KneePain,
            int HipJointPain,
            int MuscleWeakness,
            int StiffNeck,
            int SwellingJoints,
            int MovementStiffness,
            int SpinningMovements,
            int LossOfBalance,
            int Unsteadiness,
            int WeaknessOfOneBodySide,
            int LossOfSmell,
            int BladderDiscomfort,
            int FoulSmellOfUrine,
            int ContinuousFeelOfUrine,
            int PassageOfGases,
            int InternalItching,
            int ToxicLook_Typhos,
            int Depression,
            int Irritability,
            int MusclePain,
            int AlteredSensorium,
            int RedSpotsOverBody,
            int BellyPain,
            int AbnormalMenstruation,
            int DischromicPatches,
            int WateringFromEyes,
            int IncreasedAppetite,
            int Polyuria,
            int FamilyHistory,
            int MucoidSputum,
            int RustySputum,
            int LackOfConcentration,
            int VisualDisturbances,
            int ReceivingBloodTransfusion,
            int ReceivingUnsterileInjections,
            int Coma,
            int StomachBleeding,
            int DistentionOfAbdomen,
            int HistoryOfAlcoholConsumption,
            int fluid_overload,
            int BloodInSputum,
            int ProminentVeinsOnCalf,
            int Palpitations,
            int PainfulWalking,
            int PusFilledPimples,
            int Blackheads,
            int Scurring,
            int SkinPeeling,
            int SilverLikeDusting,
            int SmallDentsInNails,
            int InflammatoryNails,
            int Blister,
            int RedSoreAroundNose,
            int YellowCrustOoze)
        {
            var apiUrl = _configuration["ApiSettings:PredictionApiUrl"];
            var symptoms = new
            {
                Itching,
                SkinRash,
                NodalSkinEruptions,
                ContinuousSneezing,
                Shivering,
                Chills,
                JointPain,
                StomachPain,
                Acidity,
                UlcersOnTongue,
                MuscleWasting,
                Vomiting,
                BurningMicturition,
                SpottingUrination,
                Fatigue,
                WeightGain,
                Anxiety,
                ColdHandsAndFeet,
                MoodSwings,
                WeightLoss,
                Restlessness,
                Lethargy,
                PatchesInThroat,
                IrregularSugarLevel,
                Cough,
                HighFever,
                SunkenEyes,
                Breathlessness,
                Sweating,
                Dehydration,
                Indigestion,
                Headache,
                YellowishSkin,
                DarkUrine,
                Nausea,
                LossOfAppetite,
                PainBehindTheEyes,
                BackPain,
                Constipation,
                AbdominalPain,
                Diarrhea,
                MildFever,
                YellowUrine,
                YellowingOfEyes,
                AcuteLiverFailure,
                SwellingOfStomach,
                SwelledLymphNodes,
                Malaise,
                BlurredAndDistortedVision,
                Phlegm,
                ThroatIrritation,
                RednessOfEyes,
                SinusPressure,
                RunnyNose,
                Congestion,
                ChestPain,
                WeaknessInLimbs,
                FastHeartRate,
                PainDuringBowelMovements,
                PainInAnalRegion,
                BloodyStool,
                IrritationInAnus,
                NeckPain,
                Dizziness,
                Cramps,
                Bruising,
                Obesity,
                SwollenLegs,
                SwollenBloodVessels,
                PuffyFaceAndEyes,
                EnlargedThyroid,
                BrittleNails,
                SwollenExtremeties,
                ExcessiveHunger,
                ExtraMaritalContacts,
                DryingAndTinglingLips,
                SlurredSpeech,
                KneePain,
                HipJointPain,
                MuscleWeakness,
                StiffNeck,
                SwellingJoints,
                MovementStiffness,
                SpinningMovements,
                LossOfBalance,
                Unsteadiness,
                WeaknessOfOneBodySide,
                LossOfSmell,
                BladderDiscomfort,
                FoulSmellOfUrine,
                ContinuousFeelOfUrine,
                PassageOfGases,
                InternalItching,
                ToxicLook_Typhos,
                Depression,
                Irritability,
                MusclePain,
                AlteredSensorium,
                RedSpotsOverBody,
                BellyPain,
                AbnormalMenstruation,
                DischromicPatches,
                WateringFromEyes,
                IncreasedAppetite,
                Polyuria,
                FamilyHistory,
                MucoidSputum,
                RustySputum,
                LackOfConcentration,
                VisualDisturbances,
                ReceivingBloodTransfusion,
                ReceivingUnsterileInjections,
                Coma,
                StomachBleeding,
                DistentionOfAbdomen,
                HistoryOfAlcoholConsumption,
                fluid_overload,
                BloodInSputum,
                ProminentVeinsOnCalf,
                Palpitations,
                PainfulWalking,
                PusFilledPimples,
                Blackheads,
                Scurring,
                SkinPeeling,
                SilverLikeDusting,
                SmallDentsInNails,
                InflammatoryNails,
                Blister,
                RedSoreAroundNose,
                YellowCrustOoze
            };

            var payload = JsonConvert.SerializeObject(symptoms);
            var content = new StringContent(payload, Encoding.UTF8, "application/json");
            var response = await _httpClient.PostAsync(apiUrl, content);
            response.EnsureSuccessStatusCode();
            var result = await response.Content.ReadAsStringAsync();
            dynamic prediction = JsonConvert.DeserializeObject(result);
            return prediction.prediction;
        }
    }
}
    
