namespace MedInsight.Models
{
    public class Patient
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int Itching { get; set; }
        public int SkinRash { get; set; }
        public int NodalSkinEruptions { get; set; }
        public int ContinuousSneezing { get; set; }
        public int Shivering { get; set; }
        public int Chills { get; set; }
        public int JointPain { get; set; }
        public int StomachPain { get; set; }
        public int Acidity { get; set; }
        public int UlcersOnTongue { get; set; }
        public int MuscleWasting { get; set; }
        public int Vomiting { get; set; }
        public int BurningMicturition { get; set; }
        public int SpottingUrination { get; set; }
        public int Fatigue { get; set; }
        public int WeightGain { get; set; }
        public int Anxiety { get; set; }
        public int ColdHandsAndFeet { get; set; }
        public int MoodSwings { get; set; }
        public int WeightLoss { get; set; }
        public int Restlessness { get; set; }
        public int Lethargy { get; set; }
        public int PatchesInThroat { get; set; }
        public int IrregularSugarLevel { get; set; }
        public int Cough { get; set; }
        public int HighFever { get; set; }
        public int SunkenEyes { get; set; }
        public int Breathlessness { get; set; }
        public int Sweating { get; set; }
        public int Dehydration { get; set; }
        public int Indigestion { get; set; }
        public int Headache { get; set; }
        public int YellowishSkin { get; set; }
        public int DarkUrine { get; set; }
        public int Nausea { get; set; }
        public int LossOfAppetite { get; set; }
        public int PainBehindTheEyes { get; set; }
        public int BackPain { get; set; }
        public int Constipation { get; set; }
        public int AbdominalPain { get; set; }
        public int Diarrhea { get; set; }
        public int MildFever { get; set; }
        public int YellowUrine { get; set; }
        public int YellowingOfEyes { get; set; }
        public int AcuteLiverFailure { get; set; }
        public int SwellingOfStomach { get; set; }
        public int SwelledLymphNodes { get; set; }
        public int Malaise { get; set; }
        public int BlurredAndDistortedVision { get; set; }
        public int Phlegm { get; set; }
        public int ThroatIrritation { get; set; }
        public int RednessOfEyes { get; set; }
        public int SinusPressure { get; set; }
        public int RunnyNose { get; set; }
        public int Congestion { get; set; }
        public int ChestPain { get; set; }
        public int WeaknessInLimbs { get; set; }
        public int FastHeartRate { get; set; }
        public int PainDuringBowelMovements { get; set; }
        public int PainInAnalRegion { get; set; }
        public int BloodyStool { get; set; }
        public int IrritationInAnus { get; set; }
        public int NeckPain { get; set; }
        public int Dizziness { get; set; }
        public int Cramps { get; set; }
        public int Bruising { get; set; }
        public int Obesity { get; set; }
        public int SwollenLegs { get; set; }
        public int SwollenBloodVessels { get; set; }
        public int PuffyFaceAndEyes { get; set; }
        public int EnlargedThyroid { get; set; }
        public int BrittleNails { get; set; }
        public int SwollenExtremeties { get; set; }
        public int ExcessiveHunger { get; set; }
        public int ExtraMaritalContacts { get; set; }
        public int DryingAndTinglingLips { get; set; }
        public int SlurredSpeech { get; set; }
        public int KneePain { get; set; }
        public int HipJointPain { get; set; }
        public int MuscleWeakness { get; set; }
        public int StiffNeck { get; set; }
        public int SwellingJoints { get; set; }
        public int MovementStiffness { get; set; }
        public int SpinningMovements { get; set; }
        public int LossOfBalance { get; set; }
        public int Unsteadiness { get; set; }
        public int WeaknessOfOneBodySide { get; set; }
        public int LossOfSmell { get; set; }
        public int BladderDiscomfort { get; set; }
        public int FoulSmellOfUrine { get; set; }
        public int ContinuousFeelOfUrine { get; set; }
        public int PassageOfGases { get; set; }
        public int InternalItching { get; set; }
        public int ToxicLook_Typhos { get; set; }
        public int Depression { get; set; }
        public int Irritability { get; set; }
        public int MusclePain { get; set; }
        public int AlteredSensorium { get; set; }
        public int RedSpotsOverBody { get; set; }
        public int BellyPain { get; set; }
        public int AbnormalMenstruation { get; set; }
        public int DischromicPatches { get; set; }
        public int WateringFromEyes { get; set; }
        public int IncreasedAppetite { get; set; }
        public int Polyuria { get; set; }
        public int FamilyHistory { get; set; }
        public int MucoidSputum { get; set; }
        public int RustySputum { get; set; }
        public int LackOfConcentration { get; set; }
        public int VisualDisturbances { get; set; }
        public int ReceivingBloodTransfusion { get; set; }
        public int ReceivingUnsterileInjections { get; set; }
        public int Coma { get; set; }
        public int StomachBleeding { get; set; }
        public int DistentionOfAbdomen { get; set; }
        public int HistoryOfAlcoholConsumption { get; set; }
        public int fluid_overload { get; set; }
        public int BloodInSputum { get; set; }
        public int ProminentVeinsOnCalf { get; set; }
        public int Palpitations { get; set; }
        public int PainfulWalking { get; set; }
        public int PusFilledPimples { get; set; }
        public int Blackheads { get; set; }
        public int Scurring { get; set; }
        public int SkinPeeling { get; set; }
        public int SilverLikeDusting { get; set; }
        public int SmallDentsInNails { get; set; }
        public int InflammatoryNails { get; set; }
        public int Blister { get; set; }
        public int RedSoreAroundNose { get; set; }
        public int YellowCrustOoze { get; set; }
        public string Prognosis { get; set; } = string.Empty;
    }
}
